"use client";

import {useMemo,useState} from "react";
import {ExternalLink,ImageIcon,Plus,Trash2} from "lucide-react";
import type {FinanceItem} from "@/lib/workspace-types";
import {Field,Modal,Empty} from "./planner-fields";

const groups=[
  {kind:"income" as const,title:"Fontes de renda",description:"Cliente, salário, investimento ou qualquer outra entrada.",action:"Adicionar entrada"},
  {kind:"bill" as const,title:"Contas do mês",description:"Tudo o que precisa ser pago neste mês.",action:"Adicionar conta"},
  {kind:"planned" as const,title:"Gastos planejados",description:"Produtos salvos para consultar antes da decisão.",action:"Adicionar planejado"},
];
const money=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"});
const blank=(kind:FinanceItem["kind"]):FinanceItem=>({id:crypto.randomUUID(),owner_id:"",kind,title:"",category:"",amount:0,description:"",product_url:"",photo_url:""});

function FinanceEditor({initial,onSave,onClose}:{initial:FinanceItem;onSave:(item:FinanceItem,photo:File|null)=>Promise<void>;onClose:()=>void}){
  const [draft,setDraft]=useState(initial),[photo,setPhoto]=useState<File|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const planned=draft.kind==="planned";
  async function submit(event:React.FormEvent){event.preventDefault();setSaving(true);setError("");try{if(!draft.title.trim())throw new Error("Informe um nome.");if(!Number.isFinite(draft.amount)||draft.amount<=0)throw new Error("Informe um valor maior que zero.");await onSave({...draft,title:draft.title.trim(),category:draft.category.trim(),description:draft.description.trim(),product_url:draft.product_url.trim()},photo);onClose();}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível salvar.");}finally{setSaving(false);}}
  return <Modal title={planned?"Gasto planejado":draft.kind==="income"?"Fonte de renda":"Conta do mês"} description={planned?"Guarde a compra para consultar depois. Ela não altera o saldo previsto.":"Você pode editar ou remover este item quando precisar."} onClose={()=>{if(!saving)onClose();}}><form className="editor-form" onSubmit={submit}><fieldset disabled={saving}><Field label={planned?"O que você pretende comprar?":draft.kind==="income"?"Nome da fonte":"Nome da conta"}><input required autoFocus maxLength={240} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder={planned?"Ex.: Cadeira para escritório":draft.kind==="income"?"Ex.: Cliente Aurora":"Ex.: Aluguel"}/></Field><div className="form-grid"><Field label={planned?"Valor previsto":"Valor do mês"}><input required min="0.01" step="0.01" type="number" inputMode="decimal" value={draft.amount||""} onChange={event=>setDraft({...draft,amount:Number(event.target.value)})} placeholder="0,00"/></Field><Field label={planned?"Categoria (opcional)":"Tipo / categoria (opcional)"}><input maxLength={120} value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value})} placeholder={planned?"Ex.: Trabalho":"Ex.: Cliente, moradia"}/></Field></div>{planned&&<><Field label="Link do produto (opcional)"><input type="url" value={draft.product_url} onChange={event=>setDraft({...draft,product_url:event.target.value})} placeholder="https://..."/></Field><Field label="Foto da compra (opcional)"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>{const file=event.target.files?.[0]??null;if(file&&file.size>10*1024*1024){setError("A foto deve ter no máximo 10 MB.");event.currentTarget.value="";return;}setError("");setPhoto(file);}}/><small className="helper-text">{photo?photo.name:draft.photo_url?"Foto já salva. Escolha outra para substituir.":"JPG, PNG ou WebP, até 10 MB."}</small></Field>{draft.photo_url&&!photo&&<a className="finance-photo-link" href={draft.photo_url} target="_blank" rel="noreferrer">Abrir foto atual</a>}</>}<Field label={planned?"Descrição / motivo (opcional)":"Observação (opcional)"}><textarea rows={3} maxLength={500} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></Field>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button">{saving?"Salvando…":"Salvar"}</button></div></fieldset></form></Modal>;
}

export default function Finance({items,busy,onSave,onDelete}:{items:FinanceItem[];busy:boolean;onSave:(item:FinanceItem,photo:File|null)=>Promise<void>;onDelete:(item:FinanceItem)=>Promise<void>}){
  const [editing,setEditing]=useState<FinanceItem|null>(null),[deleting,setDeleting]=useState<string|null>(null);
  const totals=useMemo(()=>({income:items.filter(item=>item.kind==="income").reduce((sum,item)=>sum+Number(item.amount),0),bill:items.filter(item=>item.kind==="bill").reduce((sum,item)=>sum+Number(item.amount),0),planned:items.filter(item=>item.kind==="planned").reduce((sum,item)=>sum+Number(item.amount),0)}),[items]);
  const balance=totals.income-totals.bill;
  async function remove(item:FinanceItem){setDeleting(item.id);try{await onDelete(item);if(editing?.id===item.id)setEditing(null);}finally{setDeleting(null);}}
  return <><section className="finance-summary"><article className="finance-balance"><small>Saldo previsto</small><strong>{money.format(balance)}</strong><p>{balance>=0?"livre depois das contas deste mês":"as contas passam das entradas deste mês"}</p></article><article><small>Entradas</small><strong>{money.format(totals.income)}</strong></article><article><small>Contas</small><strong>{money.format(totals.bill)}</strong></article><article><small>Planejado</small><strong>{money.format(totals.planned)}</strong></article></section><div className="finance-groups">{groups.map(group=>{const rows=items.filter(item=>item.kind===group.kind);return <section className="panel finance-panel" key={group.kind}><div className="panel-heading"><div><h2>{group.title}</h2><p>{group.description}</p></div><button className="secondary-button" disabled={busy} onClick={()=>setEditing(blank(group.kind))}><Plus size={15}/>{group.action}</button></div>{rows.length?rows.map(item=><article className="finance-item" key={item.id}><div className="finance-item-row"><button className="finance-item-main" onClick={()=>setEditing(item)}><span className="finance-item-icon">{item.kind==="income"?"↗":item.kind==="bill"?"↓":"◎"}</span><span><strong>{item.title}</strong><small>{item.category||item.description||"Sem detalhes adicionados"}</small></span></button><div className="finance-item-value"><strong>{money.format(Number(item.amount))}</strong>{item.kind==="planned"&&(item.product_url||item.photo_url)&&<span>{item.product_url&&<a href={item.product_url} target="_blank" rel="noreferrer" aria-label={"Abrir link de "+item.title}><ExternalLink size={14}/></a>}{item.photo_url&&<ImageIcon size={14} aria-label="Foto adicionada"/>}</span>}</div><button className="icon-button finance-delete" disabled={busy||deleting===item.id} aria-label={"Excluir "+item.title} onClick={()=>void remove(item)}><Trash2 size={16}/></button></div>{item.kind==="planned"&&item.photo_url&&<a className="finance-photo" href={item.photo_url} target="_blank" rel="noreferrer" aria-label={"Ampliar foto de "+item.title}><img src={item.photo_url} alt={"Foto de "+item.title}/><span>Toque para ampliar</span></a>}</article>):<Empty>Adicione o primeiro item desta área.</Empty>}</section>;})}</div>{editing&&<FinanceEditor initial={editing} onSave={onSave} onClose={()=>setEditing(null)}/>}</>;
  return <><section className="finance-summary"><article className="finance-balance"><small>Saldo previsto</small><strong>{money.format(balance)}</strong><p>{balance>=0?"livre depois das contas deste mês":"as contas passam das entradas deste mês"}</p></article><article><small>Entradas</small><strong>{money.format(totals.income)}</strong></article><article><small>Contas</small><strong>{money.format(totals.bill)}</strong></article><article><small>Planejado</small><strong>{money.format(totals.planned)}</strong></article></section><div className="finance-groups">{groups.map(group=>{const rows=items.filter(item=>item.kind===group.kind);return <section className="panel finance-panel" key={group.kind}><div className="panel-heading"><div><h2>{group.title}</h2><p>{group.description}</p></div><button className="secondary-button" disabled={busy} onClick={()=>setEditing(blank(group.kind))}><Plus size={15}/>{group.action}</button></div>{rows.length?rows.map(item=><article className="finance-item" key={item.id}><div className="finance-item-row"><button className="finance-item-main" onClick={()=>setEditing(item)}><span className="finance-item-icon">{item.kind==="income"?"↗":item.kind==="bill"?"↓":"◎"}</span><span><strong>{item.title}</strong><small>{item.category||item.description||"Sem detalhes adicionados"}</small></span></button><div className="finance-item-value"><strong>{money.format(Number(item.amount))}</strong>{item.kind==="planned"&&(item.product_url||item.photo_url)&&<span>{item.product_url&&<a href={item.product_url} target="_blank" rel="noreferrer" aria-label={"Abrir link de "+item.title}><ExternalLink size={14}/></a>}{item.photo_url&&<ImageIcon size={14} aria-label="Foto adicionada"/>}</span>}</div><button className="icon-button finance-delete" disabled={busy||deleting===item.id} aria-label={"Excluir "+item.title} onClick={()=>void remove(item)}><Trash2 size={16}/></button></div>{item.kind==="planned"&&item.photo_url&&<a className="finance-photo" href={item.photo_url} target="_blank" rel="noreferrer" aria-label={"Ampliar foto de "+item.title}><img src={item.photo_url} alt={"Foto de "+item.title}/><span>Toque para ampliar</span></a>}</article>):<Empty>Adicione o primeiro item desta área.</Empty>}</section>;})}</div>{editing&&<FinanceEditor initial={editing} onSave={onSave} onClose={()=>setEditing(null)}/>}</>;
}
